DjangoBlog/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from DjangoBlog import settings
from blog import urls as blog_urls
from account import urls as account_urls
from category import urls as category_urls
from interaction import urls as interaction_urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(blog_urls)),
    path('account/', include(account_urls)),
    path('category/', include(category_urls)),
    path('action/', include(interaction_urls)),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns.append(path('__debug__/', include(debug_toolbar.urls))),

# Add static and media files to site URLs
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) \
               + static(settings.STATIC_URL, document_root=settings.STATIC_URL)

account/urls.py
from django.urls import path
from account import views as blog_views
from django.contrib.auth import views as admin_views

app_name = 'account'

urlpatterns = [
    path('', blog_views.MyAccount.as_view(), name="account"),
    path('post/', blog_views.MakePostView.as_view(), name="new_post"),
    path('edit/', blog_views.UpdateProfile.as_view(), name="update_profile"),
    path('login/', blog_views.UserLoginView.as_view(), name="login"),
    path('logout/', blog_views.UserLogoutView.as_view(), name="logout"),
    path('signup/', blog_views.UserSignUpView.as_view(), name="signup"),
]

# Add password reset URLs from django admin
urlpatterns += [
    path('password_change/', admin_views.PasswordChangeView.as_view(), name='password_change'),
    path('password_change/done/', admin_views.PasswordChangeDoneView.as_view(), name='password_change_done'),
    path('password_reset/', admin_views.PasswordResetView.as_view(), name='password_reset'),
    path('password_reset/done/', admin_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', admin_views.PasswordResetConfirmView.as_view(),
         name='password_reset_confirm'),
    path('reset/done/', admin_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
]

blog/urls.py
from django.urls import path

from blog import views as blog_views

app_name = 'blog'

urlpatterns = [
    path('', blog_views.BlogPostsView.as_view(), name="home"),
    path('blog/', blog_views.BlogPostsView.as_view(), name="homeblog"),
    path('blog/<int:pk>', blog_views.BlogPostDetailView.as_view(), name="post"),
    path('author/<int:pk>', blog_views.AuthorPostsView.as_view(), name="author"),
    path('search/', blog_views.BlogSearchView.as_view(), name="search"),
    path('bloggers/', blog_views.BloggersList.as_view(), name="bloggers"),
]

blog/models.py
from django.contrib.contenttypes.fields import GenericRelation
from django.db import models
from django.utils import timezone
from account.models import UserModel
from category.models import Category
from interaction.models import Like, Report


class BlogPost(models.Model):
    title = models.CharField(max_length=256)
    short_description = models.TextField(max_length=1024)
    content = models.TextField()
    created_date = models.DateTimeField(default=timezone.now)
    updated_date = models.DateTimeField(default=timezone.now)
    thumbnail_image = models.ImageField(null=True, blank=True)
    author = models.ForeignKey(UserModel, on_delete=models.SET_NULL, null=True, blank=True)
    category = models.ManyToManyField(Category, related_name='posts', blank=True)
    banned = models.BooleanField(default=False)
    likes = GenericRelation(Like)
    reports = GenericRelation(Report)

    class Meta:
        ordering = ['-created_date']

    def has_user_liked(self, user: UserModel):
        return self.likes.filter(user=user).exists()

    def ban(self):
        """Ban the post and automatically make all reports for this post as approved and reviewed"""
        self.reports.all().update(reviewed=True, approved=True)
        self.banned = True
        self.save()

    def remove_reports(self):
        """Mark all reports of this post as reviewed, but not approved"""
        self.reports.all().update(reviewed=True, approved=False)

    @property
    def like_count(self):
        return self.likes.count()

    @property
    def report_count(self):
        return self.reports.count()

    def __str__(self):
        return f'{self.title} {self.updated_date}'


class UserComment(models.Model):
    author = models.ForeignKey(UserModel, on_delete=models.SET_NULL, null=True, related_name='posts')
    blog_post = models.ForeignKey(BlogPost, on_delete=models.CASCADE, related_name='comments')
    comment = models.CharField(max_length=512)
    comment_date = models.DateTimeField(auto_now_add=True)
    banned = models.BooleanField(default=False)
    likes = GenericRelation(Like)
    reports = GenericRelation(Report)

    def has_user_liked(self, user: UserModel):
        return self.likes.filter(user=user).exists()

    def ban(self):
        """Ban the comment and automatically make all reports for this post as approved and reviewed"""
        self.reports.all().update(reviewed=True, approved=True)
        self.banned = True
        self.save()

    def remove_reports(self):
        """Mark all reports of this comment as reviewed, but not approved"""
        self.reports.all().update(reviewed=True, approved=False)

    @property
    def like_count(self):
        return self.likes.count()

    @property
    def report_count(self):
        return self.reports.count()

    def __str__(self):
        return f'{self.author} {self.comment_date}'

blog/forms.py
from django.forms import ModelForm

from blog.models import BlogPost


class PostForm(ModelForm):
    class Meta:
        model = BlogPost
        fields = (
            'title',
            'short_description',
            'content',
            'thumbnail_image',
            'category'
        )

blog/views.py
from django.db.models import Q
from django.http import Http404
from django.shortcuts import redirect
from django.views.generic import ListView, DetailView

from blog.models import BlogPost, UserComment, UserModel


class BlogPostsView(ListView):
    model = BlogPost
    queryset = BlogPost.objects.filter(banned=False).prefetch_related('category__parent', 'author')
    paginate_by = 6

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        pagination = context['page_obj']
        pages = []

        # Create a list of max 3 pages right and 3 pages left from the
        # current page and pas it to template as context argument
        # If there is only one page do not include in pagination
        for i in range(
                pagination.number - 3
                if pagination.number - 3 > 0 else 1,
                pagination.number + 3
                if pagination.number + 3 <= pagination.paginator.num_pages else pagination.paginator.num_pages + 1):
            pages.append(i)

        context['pages'] = pages if len(pages) > 1 else []
        return context


class AuthorPostsView(DetailView):
    model = UserModel
    template_name = 'blog/components/user_posts.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if self.object.can_post:
            user_posts = BlogPost.objects.filter(author=self.object, banned=False)
            context['posts'] = user_posts
        else:
            raise Http404()
        return context


class BlogPostDetailView(DetailView):
    model = BlogPost
    queryset = BlogPost.objects.filter(banned=False).select_related('author').prefetch_related('author', 'likes')

    def post(self, request, *args, **kwargs):
        """
        Accept POST requests for this class
        DetailView does not include this by default
        """
        self.object = self.get_object()
        self.get_context_data(request=request, object=self.object)

        # Prevent user resubmit comment by refreshing the page
        return redirect(request.path)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if self.request.method == 'POST':
            # If it is a post request check if there is a comment field
            # for current user and add it to the db
            comment = self.request.POST.get('comment')
            if comment:
                new_comment = UserComment(
                    author=self.request.user,
                    blog_post=self.object,
                    comment=comment
                )
                new_comment.save()
        comments = UserComment.objects.filter(blog_post=self.object, banned=False)
        if comments:
            context['comments'] = comments
        return context


class BloggersList(ListView):
    model = UserModel
    template_name = 'blog/authors_list.html'

    def get_queryset(self):
        queryset = super().get_queryset()
        moderator_or_author = Q(user_type__in='a') | Q(user_type__in='s')
        return queryset.filter(moderator_or_author)


class BlogSearchView(ListView):
    model = BlogPost
    queryset = BlogPost.objects.filter(banned=False)
    template_name = 'blog/blogpost_list.html'

    def get_queryset(self):
        queryset = super().get_queryset()
        query = self.request.GET.get('q')
        if not query:
            raise Http404
        search_query = Q(title__icontains=query) | Q(content__icontains=query)
        return queryset.filter(search_query, banned=False)

blog/templates/blog/components/about_author.html
{% load static %}
<div class="col s12 m7">
    <div class="card horizontal hoverable">
        <div class="card-image" style="padding: 20px">
            {% if author.avatar %}
                <img style="width: 150px; height: auto; max-height: 150px; border-radius: 50%" src="{{ author.avatar.url }}" alt="Profile picture of {{ author.author }}" class="circle">
            {% else %}
                <img style="width: 150px; height: auto" src="{% static "avatar.png" %}" alt="" class="circle">
            {% endif %}
        </div>
        <div class="card-stacked">
            <div class="card-content">
                <a href="{% url 'author' author.id %}"><h5>{{ author.username }}</h5></a>
                <p>{{ author.bio }}</p>
                <br>
                <div class="col" style="padding-left: 10px">
                    <div class="row">
                        {% if author.facebook %}
                            <a href="{{ author.facebook }}" target="_blank"><i class="fab fa-facebook-f"></i></a>
                        {% endif %}
                        {% if author.instagram %}
                            <a href="{{ author.instagram }}" target="_blank"><i class="fab fa-instagram"></i></a>
                        {% endif %}
                        {% if author.twitter %}
                            <a href="{{ author.twitter }}" target="_blank"><i class="fab fa-twitter"></i></a>
                        {% endif %}
                    </div>
                </div>
            </div>
            {% if more %}
                <div class="card-action">
                    <a href="{% url 'author' author.id %}"><p style="color: #2196F3;">More Posts</p></a>
                </div>
            {% endif %}
        </div>
    </div>
</div>

blog/templates/blog/components/breadcrumbs.html
<div class="row">
    <style>
        .breadcrumb, .breadcrumb:before, .breadcrumb:last-child {
            color: black;
        }
    </style>
    <nav style="background-color: white; box-shadow: unset !important;">
        <div class="nav-wrapper">
            <div class="col s12">
                <a href="{% url 'home' %}" class="breadcrumb">Home</a>
                {% if category %}
                    {% if category.parent %}
                        {% if category.parent.parent %}
                            <a href="{% url 'category' category.parent.parent.id %}"
                               class="breadcrumb">{{ category.parent.parent.name }}</a>
                        {% endif %}
                        <a href="{% url 'category' category.parent.id %}"
                           class="breadcrumb">{{ category.parent.name }}</a>
                    {% endif %}
                    <a href="{% url 'category' category.id %}"
                       class="breadcrumb">{{ category.name }}</a>
                {% endif %}
            </div>
        </div>
    </nav>
</div>

blog/templates/blog/components/category_card.html
<div class="col s12 m6 l4">
    <div class="card hoverable">
        <div class="card-content">
            <ul>
                <li class="collection-item">
                    <span class="title">Category: <b>{{ category.name }}</b></span>
                </li>
            </ul>
            <ul>
                <li class="collection-item">
                    <span class="title">Posts: {{ category.posts.count }}</span>
                </li>
            </ul>
        </div>
        <div class="card-action">
            <a href="{% url 'category' category.id %}" style="color: #2196F3;">Posts in this category</a>
        </div>
    </div>
</div>

blog/templates/blog/components/comments.html
{% load user_likes %}
{% load static %}
<h4>Post comments</h4>
{% if comments %}
    <ul class="collection">
        {% for comment in comments %}
            <li class="collection-item avatar">
                {% if comment.author.avatar %}
                    <img height="50" src="{{ comment.author.avatar.url }}"
                         alt="{{ comment.author.username }}" class="circle">
                {% else %}
                    <img height="50" src="{% static "avatar.png" %}" alt="" class="circle">

                {% endif %}
                <span class="title bold">{{ comment.author }} | {{ comment.comment_date }} | Likes: <span
                        id="likeCommentCount-{{ comment.id }}">{{ comment.like_count }}</span></span>
                {% if user.is_authenticated %}
                    <a class="right" href="javascript:void(0)"
                       onclick="SwitchStar(this.id, 'comment', 'likeCommentCount-{{ comment.id }}')"
                       id="comment-{{ comment.id }}">
                        {% has_user_liked content=comment user=user as is_liked %}
                        {% if is_liked %}
                            <i class="material-icons">favorite</i>
                        {% else %}
                            <i class="material-icons">favorite_border</i>
                        {% endif %}
                    </a>
                    <a class="right tooltipped" href="javascript:void(0)"
                       onclick="Report(this.id, 'comment')"
                       id="comment-report-{{ comment.id }}"
                       style="color: red; margin-right:20px"
                       data-tooltip="Report this comment">
                        {% has_user_liked content=comment user=user as is_liked %}
                        <i class="material-icons">not_interested</i>
                    </a>

                {% else %}
                    <a class="right" href="{% url 'account:login' %}" id="comment-{{ object.id }}">
                        <i class="material-icons">favorite_border</i>
                    </a>
                    <a class="right tooltipped" href="{% url 'account:login' %}" id="comment-report{{ object.id }}"
                       style="color: red; margin-right:20px" data-tooltip="Report this comment">
                        <i class="material-icons tooltipped">not_interested</i>
                    </a>
                {% endif %}
                <hr>
                <p>
                    {{ comment.comment }}
                </p>
            </li>
        {% endfor %}
    </ul>
{% else %}
    <p>No comments on this post, be the first to comment</p>
{% endif %}
{% if user.is_authenticated %}
    <h6>Make a comment</h6>
    <form class="col s12" autocomplete="off" action="{% url 'blog:post' object.id %}" method="POST">
        <div class="row">
            <div class="input-field col s12 m6">
                <input id="comment" name="comment" type="text">
                <label class="active" for="comment">Comment</label>
                {% csrf_token %}
                <div>
                    <i class="waves-effect waves-light btn blue waves-input-wrapper">
                        <input class="waves-button-input" type="submit" value="Comment" style="color: white">
                    </i>
                </div>
            </div>
        </div>
    </form>
{% else %}
    <a href="{% url 'account:login' %}"><p>Login to make comments.</p></a>
{% endif %}

blog/templates/blog/components/post.html
{% extends 'base.html' %}
{% load static %}
{% block titleblock %}
    {{ object.title }}
{% endblock %}
{% block bodyblock %}
    <div class="card hoverable">
        <div class="card-image">
            {% if object.thumbnail_image %}
                <img class="materialboxed" width="300" height="300" src="{{ object.thumbnail_image.url }}"
                     alt="{{ object.title }}">
            {% else %}
                <img width="300" height="300" src="{% static 'default.jpg' %}" alt="Default post image">
            {% endif %}
            <span class="card-title">{{ object.title }}</span>
        </div>
        <div style="padding: 20px">
            <ul>
                <li class="collection-item">
                    <i class="material-icons tiny">access_time</i>
                    <span class="title">Published: {{ object.updated_date }}</span>
                </li>
                <li class="collection-item">
                    <i class="material-icons tiny">person</i>
                    <span class="title">Author: {{ object.author.username }}</span>
                </li>
            </ul>
            <hr color="green">
            {{ object.content }}
            <br>
            <h2 class="header">About author</h2>
            {% if object.author %}
                {% include "blog/components/about_author.html" with author=object.author more=True %}
            {% endif %}
            <br>
            {% include 'blog/components/comments.html' with comments=comments %}
        </div>
    </div>
    <script>
        document.addEventListener('DOMContentLoaded', function () {
            var elems = document.querySelectorAll('.materialboxed');
            var instances = M.Materialbox.init(elems);
        });
    </script>
{% endblock %}

blog/templates/blog/components/post_card.html
{% load static %}
{% load user_likes %}
{% for post in posts %}
    <div class="col s12 m6 l4">
        <div class="card hoverable post-card">
            <div class="card-image">
                {% if post.thumbnail_image %}
                    <img width="300" height="300" src="{{ post.thumbnail_image.url }}" alt="{{ post.title }}">
                {% else %}
                    <img width="300" height="300" src="{% static 'default.jpg' %}">
                {% endif %}
                <span class="card-title">{{ post.title }}
                        </span>
            </div>
            <div class="card-content">
                <ul>
                    <li class="collection-item">
                        <i class="material-icons tiny">access_time</i>
                        <span class="title">Published: {{ post.updated_date }}</span>
                    </li>
                    <li class="collection-item">
                        <i class="material-icons tiny">person</i>
                        <span class="title">Author: {{ post.author.username }}</span>
                    </li>
                    {% if post.category.all %}
                        <li class="collection-item">
                            <i class="material-icons tiny">list</i>
                            <span class="title">Category:
                                {% for category in  post.category.all %}
                                    {{ category }}
                                {% endfor %}
                        </span>
                        </li>
                    {% endif %}
                    {% if post.banned %}
                        <li class="collection-item red">
                            <i class="material-icons tiny">not_interested</i>
                            <span class="title">This post has been banned</span>
                        </li>
                    {% endif %}
                </ul>
                <br>
                <p class="truncate">{{ post.short_description }}</p>
            </div>
            <div class="card-action">
                {% if not post.banned %}
                    <a href="{% url 'blog:post' post.id %}" style="color: #2196F3;">Read More</a>
                    {% if user.is_authenticated %}
                        <a class="right" href="javascript:void(0)" onclick="SwitchStar(this.id, 'post')"
                           id="post-{{ post.id }}">
                            {% has_user_liked content=post user=user as is_liked %}
                            {% if is_liked %}
                                <i class="material-icons">favorite</i>
                            {% else %}
                                <i class="material-icons">favorite_border</i>
                            {% endif %}
                        </a>
                    {% else %}
                        <a class="right" href="{% url 'account:login' %}" id="post-{{ post.id }}">
                            <i class="material-icons">favorite_border</i>
                        </a>
                    {% endif %}
                {% endif %}
            </div>
        </div>
    </div>
{% endfor %}

blog/templates/blog/components/user_posts.html
{% extends 'base.html' %}
{% load static %}
{% block titleblock %}
    Author {{ object.user.username }}
{% endblock %}
{% block bodyblock %}
    <div>
        <h2 class="header">About author</h2>
        {% include 'account/components/about_author.html' with author=object %}
    </div>
    <div class="row">
        <h5>Posts from {{ object.username }}</h5>
        {% include 'blog/components/post_card.html' %}
    </div>
{% endblock %}