DjangoBlog/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from DjangoBlog import settings
from blog import urls as blog_urls
from account import urls as account_urls
from category import urls as category_urls
from interaction import urls as interaction_urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(blog_urls)),
    path('account/', include(account_urls)),
    path('category/', include(category_urls)),
    path('action/', include(interaction_urls)),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns.append(path('__debug__/', include(debug_toolbar.urls))),

# Add static and media files to site URLs
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) \
               + static(settings.STATIC_URL, document_root=settings.STATIC_URL)

account/urls.py
from django.urls import path
from account import views as blog_views
from django.contrib.auth import views as admin_views

app_name = 'account'

urlpatterns = [
    path('', blog_views.MyAccount.as_view(), name="account"),
    path('post/', blog_views.MakePostView.as_view(), name="new_post"),
    path('edit/', blog_views.UpdateProfile.as_view(), name="update_profile"),
    path('login/', blog_views.UserLoginView.as_view(), name="login"),
    path('logout/', blog_views.UserLogoutView.as_view(), name="logout"),
    path('signup/', blog_views.UserSignUpView.as_view(), name="signup"),
]

# Add password reset URLs from django admin
urlpatterns += [
    path('password_change/', admin_views.PasswordChangeView.as_view(), name='password_change'),
    path('password_change/done/', admin_views.PasswordChangeDoneView.as_view(), name='password_change_done'),
    path('password_reset/', admin_views.PasswordResetView.as_view(), name='password_reset'),
    path('password_reset/done/', admin_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', admin_views.PasswordResetConfirmView.as_view(),
         name='password_reset_confirm'),
    path('reset/done/', admin_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
]

blog/urls.py
from django.urls import path

from blog import views as blog_views

app_name = 'blog'

urlpatterns = [
    path('', blog_views.BlogPostsView.as_view(), name="home"),
    path('blog/', blog_views.BlogPostsView.as_view(), name="homeblog"),
    path('blog/<int:pk>', blog_views.BlogPostDetailView.as_view(), name="post"),
    path('author/<int:pk>', blog_views.AuthorPostsView.as_view(), name="author"),
    path('search/', blog_views.BlogSearchView.as_view(), name="search"),
    path('bloggers/', blog_views.BloggersList.as_view(), name="bloggers"),
]

category/urls.py
from django.urls import path

from category import views as category_views

app_name = 'category'

urlpatterns = [
    path('<int:pk>', category_views.CategoryPostsView.as_view(), name="category"),
    path('', category_views.CategoryView.as_view(), name="categories"),
]

interaction/urls.py
from django.urls import path

from interaction import views

app_name = 'interaction'

urlpatterns = [
    path('like/post/<int:post_id>', views.like_post, name="like_post"),
    path('like/comment/<int:comment_id>', views.like_comment, name="like_comment"),

    path('report/post/<int:post_id>', views.report_post, name="report_post"),
    path('report/comment/<int:comment_id>', views.report_comment, name="report_comment"),

    path('report/post/remove/<int:post_id>', views.ignore_reports_post, name="accept_report_post"),
    path('report/post/ban/<int:post_id>', views.ban_post, name="ban_report_post"),
    path('report/comment/remove/<int:comment_id>', views.ignore_reports_comment, name="accept_report_comment"),
    path('report/comment/ban/<int:comment_id>', views.ban_comment, name="ban_report_comment"),

    path('reports/posts', views.ReportedPosts.as_view(), name="reported_posts"),
    path('reports/comments', views.ReportedComments.as_view(), name="reported_comments"),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Compiled and minified CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">

    <!-- Compiled and minified JavaScript -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>

    <!-- Material icons and FontAwesome -->
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/css/all.min.css"
          integrity="sha512-+4zCK9k+qNFUR5X+cKL9EIR+ZOhtIloNl9GIKS57V1MyNsYpYcUrUeQc9vNfzsWfV28IaLL3i96P9sdNyeRssA=="
          crossorigin="anonymous"/>
    <script src="{% static 'main.js' %}"></script>
    <style>
        .post-card {
            min-height: 543px;
        }
    </style>
    <title>
        {% block titleblock %}
        {% endblock %}
    </title>
</head>
<body>
{% include 'header.html' %}
<div style="padding: 20px">
    {% block bodyblock %}
    {% endblock %}
</div>
<script>
    document.addEventListener('DOMContentLoaded', function () {
        M.AutoInit();
    });
</script>
{% include 'footer.html' %}
</body>
</html>

templates/breadcrumbs.html
<div class="row">
    <style>
        .breadcrumb, .breadcrumb:before, .breadcrumb:last-child {
            color: black;
        }
    </style>
    <nav style="background-color: white; box-shadow: unset !important;">
        <div class="nav-wrapper">
            <div class="col s12">
                <a href="{% url 'blog:home' %}" class="breadcrumb">Home</a>
                {% if category %}
                    {% if category.parent %}
                        {% if category.parent.parent %}
                            <a href="{% url 'category:category' category.parent.parent.id %}"
                               class="breadcrumb">{{ category.parent.parent.name }}</a>
                        {% endif %}
                        <a href="{% url 'category:category' category.parent.id %}"
                           class="breadcrumb">{{ category.parent.name }}</a>
                    {% endif %}
                    <a href="{% url 'category:category' category.id %}"
                       class="breadcrumb">{{ category.name }}</a>
                {% endif %}
            </div>
        </div>
    </nav>
</div>

templates/footer.html
<footer class="page-footer" style="background-color: #2196F3 !important">
    <div class="container">
        <div class="row">
            <div class="col l6 s12">
                <div class="row">
                    <div class="col s12">
                        <h5 class="white-text">What is DjangoBlog</h5>
                        <p class="grey-text text-lighten-4">DjangoBlog is a blog build using django for a project</p>
                    </div>
                </div>
                <div class="row">
                    <form action="{% url 'blog:search' %}" class="col s12">
                        <div class="row">
                            <div class="input-field col s12">
                                <input placeholder="Search" id="q" type="text" class="validate" name="q" style="color: whitesmoke" value="{{ request.GET.q }}">
                                <label for="first_name" style="color: lightgray">Want so search something?</label>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
            <div class="col l4 offset-l2 s12">
                <h5 class="white-text">Links</h5>
                <ul>
                    <li><a class="grey-text text-lighten-3" href="{% url 'blog:home' %}">All posts</a></li>
                    <li><a class="grey-text text-lighten-3" href="{% url 'blog:bloggers' %}">Bloggers</a></li>
                    <li><a class="grey-text text-lighten-3" href="{% url 'category:categories' %}">Categories</a></li>
                    {% if user.is_authenticated %}
                        <li><a class="grey-text text-lighten-3" href="{% url 'account:account' %}">Account</a></li>
                        <li><a class="grey-text text-lighten-3" href="{% url 'account:logout' %}">Logout</a></li>
                    {% else %}
                        <li><a class="grey-text text-lighten-3" href="{% url 'account:login' %}">Login</a></li>
                        <li><a class="grey-text text-lighten-3" href="{% url 'account:signup' %}">Signup</a></li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </div>
    <div class="footer-copyright">
        <div class="container">
            ©
            <script>document.write(new Date().getFullYear())</script>
            Copyright DjangoBlog
            <a class="grey-text text-lighten-4 right" target="_blank"
               href="https://github.com/clirimfurriku/DjangoBlog">GitHub</a>
        </div>
    </div>
</footer>

templates/header.html
<nav>
    <div class="nav-wrapper blue" style="padding-left: 10px; padding-right: 10px">
        <a href="{% url 'blog:home' %}" class="brand-logo">DjangoBlog</a>
        <a href="#" data-target="mobile-demo" class="sidenav-trigger"><i class="material-icons">menu</i></a>
        {% if user.is_staff %}
            <ul id="dropdown1" class="dropdown-content">
                <li class="divider"></li>
                <li><a href="{% url 'interaction:reported_posts' %}">Reported posts</a></li>
                <li><a href="{% url 'interaction:reported_comments' %}">Reported comments</a></li>
            </ul>
        {% endif %}
        <ul id="nav-mobile" class="right hide-on-med-and-down">
            {% if user.is_authenticated %}
                <li><b>Hey {{ user }}!</b></li>
            {% endif %}
            <li><a href="{% url 'blog:home' %}">All posts</a></li>
            <li><a href="{% url 'blog:bloggers' %}">Authors</a></li>
            <li><a href="{% url 'category:categories' %}">Categories</a></li>
            {% if user.is_authenticated %}
                <li><a href="{% url 'account:account' %}">Account</a></li>
                {% if user.is_staff %}
                    <li><a class="dropdown-trigger" href="#!" data-target="dropdown1">Reports<i
                            class="material-icons right">arrow_drop_down</i></a></li>
                {% endif %}
                <li><a href="{% url 'account:logout' %}">Logout</a></li>
            {% else %}
                <li><a href="{% url 'account:login' %}">Login</a></li>
                <li><a href="{% url 'account:signup' %}">Sign Up</a></li>

            {% endif %}
        </ul>
    </div>
</nav>

{# Mobile menu #}
<ul class="sidenav" id="mobile-demo">
    {% if user.is_authenticated %}
        <li><b class="center-align" style="padding: 20px">Hey {{ user }}!</b></li>
    {% endif %}
    <li><a href="{% url 'blog:home' %}">All posts</a></li>
    <li><a href="{% url 'blog:bloggers' %}">Authors</a></li>
    <li><a href="{% url 'category:categories' %}">Categories</a></li>
    {% if user.is_authenticated %}
        <li><a href="{% url 'account:logout' %}">Logout</a></li>
    {% else %}
        <li><a href="{% url 'account:login' %}">Login</a></li>
        <li><a href="{% url 'account:signup' %}">Sign Up</a></li>

    {% endif %}
</ul>